[tool.poetry]
name = "asyncpgx"
version = "1.0.0"
description = ""
authors = ["Vladislav Laukhin <vladislav.laukhin@raiffeisen.ru>"]

[tool.poetry.dependencies]
python = "^3.8"
asyncpg = "^0.21.0"
pytest-cov = "^2.10.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
pylint = "^2.6.0"
mypy = "^0.782"
isort = "^5.5.3"
docformatter = "^1.3.1"
pytest = "^6.1.0"
pyre-check = "^0.0.56"

[tool.black]
line-length = 120
target-version = ["py38"]
include = '\.pyi?$'
skip-string-normalization = true
exclude = '''
(
  /(
    | \.git
    | \.mypy_cache
  )/
)
'''

[tool.isort]
line_length = 120
sections = ['FUTURE', 'STDLIB', 'THIRDPARTY', 'FIRSTPARTY', 'LOCALFOLDER']
no_lines_before = ['STDLIB', 'LOCALFOLDER']
known_third_party = [
    'pytest',
]
known_local_folder = []
multi_line_output = 3
lines_after_imports = 2

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
