name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: ubuntu:18.04

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Install python
        run: |
             apt update -y
             apt install -y software-properties-common
             add-apt-repository -y ppa:deadsnakes/ppa
             apt install -y python3.8 python3.8-pip python3.8-dev

      - name: Install poetry
        run: |
             python3 -m pip install --upgrade pip
             pip install poetry
             poetry config virtualenvs.create false
        
      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: pylint asyncpgx

      - name: Run mypy
        run: mypy asyncpgx
        
      - name: Run pytest
        run: pytest . --cov-report=xml --cov=.
        env:
          POSTGRESQL_TEST_DSN: postgresql://postgres:5432

      - name: Push test coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: e20b12a9-9293-47fb-8e40-12f6e156f7e4
