name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest
    container: debian:10.5-slim

    services:
      postgres:
        image: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install poetry
        run: |
             pip install poetry
             poetry config virtualenvs.create false
        
      - name: Install dependencies
        run: poetry install

      - name: Run pylint
        run: pylint asyncpgx

      - name: Run mypy
        run: mypy asyncpgx
        
      - name: Run pytest
        run: pytest . --cov-report=xml --cov=.
        env:
          POSTGRESQL_TEST_DSN: postgresql://postgres:5432

      - name: Push test coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: e20b12a9-9293-47fb-8e40-12f6e156f7e4
